# Supabase Configuration

[api]
enabled = true
port = 54321

[functions.ai-ingredient-assistant]
verify_jwt = false

[functions.spelling-corrector]
verify_jwt = false

[functions.monitor-menus]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
